### ISSUE TITLE
[BUG] FiveM crash/reconnects?

### ISSUE THREAD

**Issue by nofacetv** [E66666666/GTAVManualTransmission#102]
**Describe the bug**
FiveM, once in a vehicle, Gears.ASI loads, then dissapears, and randomly reconnects, making it useable for about 30 seconds at a time before it stops then starts again

**To Reproduce**
Steps to reproduce the behavior: have it enabled in server

**Expected behavior**
A clear and concise description of what you expected to happen. for it to work normally as it used to

**Screenshots and/or videos**
If applicable, add screenshots or video to help explain your problem.

**Used versions and additional hardware:**
 - Game version: [e.g. 1.0.1337.1 on Steam) FiveM 29.6.7
 - Mod version: [e.g. v4.6.7, AppVeyor build] 5.0.0
 - Additional hardware: [e.g. Logitech G29, Xbox One controller] ThrustMaster T150

**Settings, if applicable:**
 - If applicable, link to settings_general.ini
 - If applicable, link to settings_wheel.ini

**Additional context**

**Comment by E66666666** [comment]
I'm aware that this stopped working on FiveM. It's probably due to a recent change in the FiveM client.

I don't have time to spend on finding out what's actually wrong, so I'll probably just remove the claimed compatibility with FiveM. Feel free to re-open this issue if you find out what's actually wrong or have some solid pointers to a fix.

**Comment by nofacetv** [comment]
Ill take a peak around, it doesnt seem to "NOT WORK" on fiveM anymore but rather it seems that FiveM is just having a hard time Keeping it running for some reason. but when it does run it works fine, just disconnects and reconnects

**Comment by E66666666** [comment]
The last time I checked things, it worked when the FiveM GTA process executable was on version 1604. This probably changed to 2060.

FiveM manages script lifetime, so check the FiveM client source for changes around these things.

**Comment by E66666666** [comment]
I'm closing this again, it seems to be happening since the "November Update" to most client-side scripts.

I can't test it since FiveM just decides to die when I spawn a car.

**Comment by nofacetv** [comment]
any thought of opening this back up? im willing to help you in anyway i can, id even be willing to pay for this as its wanted by ALOT of the FiveM community as of late

**Comment by E66666666** [comment]
No. It works fine on SP. Anything that claims it supports ScriptHookV scripts should also work. It's not my problem FiveM randomly changes stuff that breaks SHV compatibility.
