### ISSUE TITLE
[BUG] CRASH - FUEL MOD

### ISSUE THREAD

**Issue by Visual917** [E66666666/GTAVManualTransmission#106]
Fuel mod crashes. Can you help please? 

Win 10, Steam, I have Redux, Manual Transmission, and also the speedometer installed. The HUD menu works but the ASI crashes when I enter a car.

**Comment by Visual917** [comment]
Also I have crazy motion blur when driving in FPS mode. One of these mods cause that.

**Comment by Visual917** [comment]
OK. Manual transmission causes that.

**Comment by E66666666** [comment]
Motion blur: Caused by the custom camera in conjunction with another mod that increases motion blur. Either disable the custom camera or disable the exaggerated motion blur mod.

No idea on the fuel mod, worked last time I tried it and this issues page is not intended for that anyway.

**Comment by Visual917** [comment]
Ok. @E66666666 You don't have an issues page for the fuel mod. It just doesn't work.
