### ISSUE TITLE
Speedometer RPM not displaying

### ISSUE THREAD

**Issue by GorrakTheOriginal** [E66666666/GTAVManualTransmission#107]
While I can get the gear and speed to display no problem the rmp is hidden and I really dont know why or how to fix it. After activating it I have tried moving the location and size but it is nowhere on the screen.
Is something different with this gauge?
Edit: I should also mention that I am playing in vr using the REAL mod

**Comment by E66666666** [comment]
Make sure the sizes are bigger than zero. Also check without VR to see where it is on-screen.

The thing is drawn using rectangles (the same kind the menu uses) so it should be visible.

**Comment by GorrakTheOriginal** [comment]
Ok, I discovered that I can see the rpm meter....but only when I am aiming with a gun in the car!!
Then it appears normally but goes away again as soon as I stop. It does not matter where I place it, as soon as I lower my weapon it disappears so I think it must be linked to the view change that happens when going from driving to driving and aiming/shooting.
Any ideas?

**Comment by E66666666** [comment]
Try disabling the custom first person camera. (Misc options)

**Comment by GorrakTheOriginal** [comment]
Yes you legend, that was it!!!

Also for an added bonus now the camera doesn't twitch to straight ahead every time I pull a gun out. Now I just have to get used to not using that to center my view, haha!

Thanks :)

**Comment by E66666666** [comment]
Glad it's resolved :)

**Comment by VixusFoxy** [comment]
I'm going to reopen this with the request to make the functionality work with custom FPV camera. I'm utilizing this mod alongside a VR (R.E.A.L) mod and the head movement is not good if I turn the custom FPV off -- all other indicators work fine with the mode enabled, why not also this one? :)
