### ISSUE TITLE
Compatibility with R.E.A.L. mod

### ISSUE THREAD

**Issue by LukeRoss00** [E66666666/GTAVManualTransmission#108]
Hi! A few of our common users are having trouble again due to the custom FPV camera. I was surprised because I remembered you checking for `RealVR.asi` and automatically disabling it if the module was found, so I browsed through your commits and I saw that at some point you removed the detection code.

May I ask why you did that? It's causing a subpar experience for some people...

**Comment by E66666666** [comment]
Some users specifically requested the custom camera to be enabled again during VR, so I disabled the detection and made disabling the FPV camera an option, in Debug -> Compatibility.

**Comment by LukeRoss00** [comment]
Weird that they should ask for that, because others are saying that it causes distortion/warping of the view, and that it makes the camera fly into the dashboard. Oh, I see that you replied to the other thread, so I'll continue [there](https://github.com/LukeRoss00/gta5-real-mod/issues/339)
