### ISSUE TITLE
Problematic wheels

### ISSUE THREAD

**Issue by E66666666** [E66666666/GTAVManualTransmission#109]
The following wheels seem to be troublesome:

* Logitech G920 (+ ScriptHookVDotNet)
* Thrustmaster TMX

Both of these devices seem to be optimized for Xbox. Why this would cause issues with the DirectInput I use - I don't know, seems to have to do with force feedback.

Might want to look into using a newer DirectInput library or even switch the whole thing over to WinRT's `Windows.Gaming.Input`.

**Comment by dellbearwood** [comment]
Update it. I got A G29
G29 + ScriptHookV.net
I advise to remove scripthookv.net as it thinks the Manual transmission folder is its own other script fold

**Comment by E66666666** [comment]
Hmm, most of this should be covered in #17, so I'm closing this one.
