### ISSUE TITLE
Add dead zone, invert and curves for axises for more smooth reaction.

### ISSUE THREAD

**Issue by VladimirPobedinskiy** [E66666666/GTAVManualTransmission#11]
Add dead zone, invert and curves for axises for more smooth reaction.
![000000001](https://cloud.githubusercontent.com/assets/198486/25090606/95689e30-23c7-11e7-8995-748eda1ef74a.png)

**Comment by E66666666** [comment]
a9a53918d9b93fe74969bb5e3baf4203558f54d5 automatically allows for deadzones on combined pedals (separate pedals already had this by nature). Will see what I can do with curve and/or I will invert this. You can invert this manually by swapping min/max values btw.

**Comment by E66666666** [comment]
57ad42f16755714a36bbcd15064c8dbc51e6bd24 added invert
f575d46d2e8ed0b25099bfb5091e87bf9cadd33b added anti-deadzone

Will not add deadzone as the previously mentioned commit a9a53918d9b93fe74969bb5e3baf4203558f54d5 already allows for deadzone in config.

Will not add nonlinear axes because I'm lazy.
