### ISSUE TITLE
How to disable autobrake?

### ISSUE THREAD

**Issue by Bluscream** [E66666666/GTAVManualTransmission#115]
I can't find a option to disable the automatic braking once i release the gas pedal. Can you tell me how i do that?

**Comment by E66666666** [comment]
There is no "autobrake" option.

- If you find the usual engine resistance from the game too much, enable the [`HF_FREEWHEEL_NO_GAS`](https://github.com/E66666666/GTAVHandlingInfo/blob/0e6c8985c5faeedf21539086eac391e691ee8cc7/flags.json#L166) flag for the affected vehicles.
- If you somehow ended up configuring the analog brake for your wheel where at rest it registers as (partially) pressed, re-assign the axis and follow the onscreen instructions again.
