### ISSUE TITLE
See Comment - Totally irrelevant to GTAVMT but I didn't know any other way of asking.

### ISSUE THREAD

**Issue by Nerxxy** [E66666666/GTAVManualTransmission#123]
Could you make a replacement handling.meta for Zetto's (BolinhodeVenus on gta5-mods) R33? For some reason its really slippery and when I try to edit it myself the game either gives me "err_fil_pack_3" or the car tips over on every corner, I've tried copying other handling files, using your Real Time Handling Editor and read documentation on what each option does but I still cant get my head around it.

So if you have the time I would greatly appreciate it <3

**Comment by E66666666** [comment]
Sorry, no.
