### ISSUE TITLE
[FEATURE] - Re-enable Mid-air Control 

### ISSUE THREAD

**Issue by Nerxxy** [E66666666/GTAVManualTransmission#124]
**What does this feature relate to?**
general options

**Describe the solution you'd like**
To be able to control my car when flying through the air

**Comment by E66666666** [comment]
just turn off custom steering

**Comment by Nerxxy** [comment]
Where is that option?

**Comment by Nerxxy** [comment]
@E66666666 where do I find the option?

**Comment by Nerxxy** [comment]
nvm figured it out
