### ISSUE TITLE
not work ( not showed up )

### ISSUE THREAD

**Issue by AlaaAshraf1991** [E66666666/GTAVManualTransmission#126]
**Describe the bug**
i added the mod and not showed up.

this mod (Manual Transmission ) not respond with me , nothing showed up when I raid , nothing showed when I Writes the code in the game .. like I never add the mod ?????? I did all the installation steps one by one with every vid I saw in youtube and nothing happened I even reinstall the game......... plz help..

![171567677-7f7ba660-e4f9-461a-bc34-88eb1db0e28c](https://user-images.githubusercontent.com/106727588/171570318-ff1c47b5-b48e-43d5-b783-7a2276ec7d14.jpg)

**Comment by E66666666** [comment]
Duplicate of #125
