### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by swagnamite** [E66666666/GTAVManualTransmission#133]
**Describe the bug**
G29 gets recognized correctly (first launch of the mod = Logitech G29 with green background under wheel settings), but the menu says Device not connected [-1]. Under Analog input I can assign every single button/axis with a 10 second game freeze, and it does get recognized as Device [0] Logitech G29, it recognizes i.e. the throttle axis correctly when I press/depress the pedal, but when I go back to general wheel settings it's still Device [-1] disconnected and the wheel doesn't work in-game. I used WheelSetup.exe and it gets recognized with no problems (no other devices are detected there, nothing else is listed in Gears.log either, so why does it keeps looking for device [-1] if my wheel is device [0]?

**To Reproduce**
Launch the game + mod with G29 connected

**Expected behavior**
The wheel should be fully recognized and working

**Screenshots and/or videos**
If applicable, add screenshots or video to help explain your problem.
![wheel1](https://user-images.githubusercontent.com/58146630/192915117-59a63b57-3d00-4127-b81e-362d4f68906e.png)
![wheel2](https://user-images.githubusercontent.com/58146630/192915152-1acc758e-6822-4d97-aecd-641d98b5df66.png)

**Used versions and additional hardware:**
 - Game version: 1.0.2699.0, rockstar launcher (I realize that this is a new, unsupported version, but I'm hoping there's a fix that I don't see before I rollback)
 - Mod version: tried 5.5.1, 5.5.0 and 5.4.2 (I used the mod with no problems back when 5.4.2 was the latest, now it doesn't work either)
 - Additional hardware: Logitech G29, tried multiple Logitech G Hub versions, dating as far as 2020, deleted the app completely with registry keys etc.

**Settings, if applicable:**
 - If applicable, link to settings_general.ini
https://pastebin.com/puLfNpHw
 - If applicable, link to settings_wheel.ini
https://pastebin.com/XDE1Jtyr

**Additional context**
Gears.asi seems to find a problem with initializing ffb, https://pastebin.com/65km7dSf

**Comment by E66666666** [comment]
It's probably a problem with permissions, it can't write to the GTA V folder?

Try using the newest version and configure everything again. It should use the `%localappdata%\ikt\ManualTransmission` folder when it detects this happening.

**Comment by swagnamite** [comment]
I deleted the mod, pasted the newest version (5.4.1), claimed the ownership of the GTA V folder, subfolder and files, gave every single localgroup full control - it still says that Device is not connected [-1] instead of using the detected device [0] from "Analog input" submenu, Gears.log still says ffb initialization failed and "But axis is unknown? Axis: 8". 
![wheel3](https://user-images.githubusercontent.com/58146630/193070197-9a29ba87-76c2-4747-93b8-763b98d88ff0.png)


Also, no folder gets created in any of the 3 appdata subfolders, everything is written in the GTA V/ManualTransmission folder, not really sure what causes that if you're saying that it should write into %localappdata%.

**Comment by E66666666** [comment]
5.5.1 you mean?

If everything is written in GTA V/ManualTransmission, then it's not a file permission error. You sure re-registering the axes doesn't work?

**Comment by swagnamite** [comment]
yeah, I meant 5.5.1, my bad.
Let me try to explain a bit better, registering the axes works only in the "Analog inputs" sub-menu, as per the screenshot above we can see that I successfully registered the throttle pedal to "Throttle", I pressed it lightly at the moment of making the screenshot to show that it's detected properly, the sub-menu also reads the device itself as Device: [0] G29 etc., so it looks fine, right?

Then I get back one page, to the "Wheel and pedals" sub-menu, and this sub-menu says that the device [-1] is disconnected, no mention of G29 or even Device [0] at all. So I can register everything in the Analog input sub-menu properly, all buttons and all axes, but as soon as I go back/close the menu nothing works, no steering, no buttons, no pedals, no forcefeedback (the wheel itself feels like it's disconnected, but it's worth noting that the moment I alt-tab/lose focus the wheel jumps to straight position)

It really feels like the menu is looking for a wrong input device, but I do not have anything else connected, I even tried disconnecting the keyboard itself. Perhaps there are some residues of devices in registry/device manager still has drivers for something like xbox controller or something like that and the menu reads it as a device that is, in fact, disconnected? Also I don't know if you looked into the files I sent, but there is that issue with FFB initialization in gears.log, in this case I have no idea what might be causing it, or if it's connected to the issue at hand. Let me know what you think, cheers.

**Comment by E66666666** [comment]
That doesn't sound like a device issue, but a configuration write issue.

The `settings_wheel.ini` you linked (https://pastebin.com/XDE1Jtyr) is the default file that comes with the mod, which is why I think it's a file permission error.

Try copying the ManualTransmission folder to `%localappdata%/ikt`. (Create an `ikt` folder in `C:\Users\<your_account>\AppData\Local`, and copy the `ManualTransmission` folder there).

Really odd you don't seem to get errors about failure to write, though.

**Comment by swagnamite** [comment]
Right, so now it does write the settings

[THROTTLE]
GAMMA = 1.000000
ANTIDEADZONE = 0.250000
DEVICE = 0
AXIS = lY
MIN = 65535
MAX = 0


[BRAKE]
GAMMA = 1.000000
ANTIDEADZONE = 0.250000
DEVICE = 0
AXIS = lRz
MIN = 65535
MAX = 0

and they get read properly when I launch the game again (it's still assigned in Analog input), but the wheel is still only found in that sub-menu, the Wheel and pedals menu still says "device [-1] is disconnected" and the assigned input doesn't do anything (besides, of course, the Analog input sub-menu, where I can press/depress it and see that it works, the menu does see that I'm pressing/depressing the pedal or button, since it's the only place where the input device is properly recognized)

Also I realize I'm unintentionally making this harder than it needs to be, but after fucking around a bit more with permissions/installing older versions and whatnot earlier it did write to the settings_wheel.ini correctly (the game folder version, not the %localappdata% version, the throttle was assigned as above), I just didn't update the pastebin. After pasting the folder to appdata/local/ikt it doesn't write to the game folder anymore, but it does write to the appdata one without issue (well, except it still finds the device disconnected, of course)

**Comment by E66666666** [comment]
@swagnamite 

`-1` is indeed a value for "no device".

As it stands, the throttle and brake look mapped correctly. Steering does not look mapped. If you set up the steering wheel, everything else should start working.

**Comment by swagnamite** [comment]
that's a certified bruh moment™ if i've ever seen one

in my defense, I had no idea that if I don't assign the steering itself the device wouldn't be recognized at all, and it certainly didn't work at the time when I had the permissions messed up. While the game freezing persists, I only need to get through configuration once, so it's not going to be a problem later. Thanks for the help, cheers :).
