### ISSUE TITLE
Crashes with a Logitech G920 and ScriptHookVDotNet v2.

### ISSUE THREAD

**Issue by jcostamagna** [E66666666/GTAVManualTransmission#17]
For me it would be very usefull to have it working. What is the exception that throws here? Perhaps we can get help.

Cheers.

**Comment by E66666666** [comment]
This is a known issue as indicated in the readme and the mod description over at GTA5-Mods.com

If you have some experience debugging mods for this game, try finding the line(s) where it throws the exception. (Attach with Visual Studio after building a debug version with symbols)

Alternatively try an automated build, maybe some other changes fixed it.

**Comment by jcostamagna** [comment]
@E66666666 I don't have experience but i was trying to attach it and crashes before now.
I try to catch the exception from your mod but i couldn't.
You have more experience? Any ideas?

**Comment by E66666666** [comment]
@jcostamagna 
Disable all ScriptHookVDotNet scripts (simply rename the `scripts` folder) and try again. Somehow it doesn't throw exceptions with no .NET scripts. If you mean during loading, don't attach yet. 

Try going in-game first (and not in a vehicle) and then attach VS.

**Comment by jcostamagna** [comment]
@E66666666 
When I get out of the game to attach it, crash it self :/ 

So i can't try that. 

Should be another way to debbug this. Any tool?

**Comment by E66666666** [comment]
@jcostamagna 
VS should work fine, or x64dbg. I'd look around the DiJoyStick class and WheelDirectInput classes specifically and just put breaks there.

Also just enable the script reloading thing for SHV, remove all scripts from SHVDN and then see where it goes wrong.

Or simply put log statements everywhere in the code and run it normally :p

**Comment by E66666666** [comment]
I made [a build to test](https://github.com/E66666666/GTAVManualTransmission/releases/tag/v4.4.1-g920-trace) when things go wrong. It dumps the stack trace to the log file, and might help me with fixing this.

If anybody could please help. @jcostamagna ?

**Comment by E66666666** [comment]
It crashes at GetCapabilities in DiJoystick.h and CreateEffect in WheelDirectInput.cpp.

Commenting out the GetCapabilities stops the crashing on start, but can't get around needing to set up an effect.

Please help, somebody. Why is the G920 so weird when using ScriptHookVDotNet?

**Comment by E66666666** [comment]
Here's a mirror of the driver Logitech made for BeamNG.
[LGS_ForceFeedback_Fix_01022007.zip](https://github.com/E66666666/GTAVManualTransmission/files/1485205/LGS_ForceFeedback_Fix_01022007.zip)

**Comment by E66666666** [comment]
When preparing for CreateEffect, the Logitech example does this:

* Check for XInput
* Else
  * SetDataFormat - same params I have
  * SetCooperativeLevel - same params I have
* More other stuff to set up their own FFB classes etc
* CreateEffect with the same params I have

Only difference now is that I don't do the Xinput branch, but my code's been working fine with using an Xbox 360 controller as wheel/DirectInput device... Only XInput API call it does is `XInputGetState` anyway.

Also doesn't explain why it only crashes and burns when ScriptHookVDotNet is *also* active.

**Comment by E66666666** [comment]
As of a few months ago, somebody on 5mods discovered that everything works fine if the game is launched via the RAGEPluginHook launcher. 

For me this is still not an acceptable solution, but it is a feasible workaround.

**Comment by E66666666** [comment]
As for the latest releases, it seems that the issue somehow has disappeared. I'm closing this issue now, but if you have repeatable crashes with a G920 + ScriptHookVDotNet, please let me know again.

**Comment by E66666666** [comment]
Issue reared its ugly head again after/since... 5.0.0?

Anyway, problem seems to also affect G29's when G Hub is used - after the most recent update, `2021.5.9841`, released on May 27th.

Got no clue what it could be, but signs point to initializing the FFB once again - so I guess it's `CreateEffect` acting up again.

**Comment by Bluscream** [comment]
I have this issue on FiveM currently on my own server

**Comment by E66666666** [comment]
An update on the situation:

I've rewritten the directinput initialization part, to get rid of the need of reinitializing the wheel constantly. This might solve the issue, but I haven't heard back from any users yet.

As for the source of the problem, it seems like creating an effect for a device twice, causes a simple access violation somewhere - as G29/G Hub users don't seem to use SHVDN.

**Comment by E66666666** [comment]
Seem to have solve this in e54976a.
