### ISSUE TITLE
Option to make driving wheel work even when window is out of focus.

### ISSUE THREAD

**Issue by mohirio** [E66666666/GTAVManualTransmission#21]
Hi!

I was wondering if you add an option that allows driving wheel controls persists even if GTAV window is out of focus. 

It would be really helpful to move the mouse around in windowed mode and not having to focus back on the game to drive.

Much appreciated!

**Comment by E66666666** [comment]
I've been having some trouble getting DirectInput to work reliably in the background.

**Comment by mohirio** [comment]
Do you think it has something to do the game to avoid cheating?

So for example if you go single player mode and apply any cheat and then try to use the wheels, it might allow direct input to work without the window being on focus.

Just a thought.

**Comment by E66666666** [comment]
Not really, it's just how force feedback and DirectInput seem to work. I'm not feeling it to change it: The wheel gets rather unreliable even when focused when I allow it to work in the background.
