### ISSUE TITLE
VehicleData and VehicleExtension for new version

### ISSUE THREAD

**Issue by n-akram** [E66666666/GTAVManualTransmission#23]
Hi,

I have been following your project for one of my own. I was using your libraries to obtain vehicleData for log. 

But after recent update (on 12-12-2017),  these libraries no longer seems to work. My GTA 5 version is currently v1.2.3.1.

Can you help me with this? I just want vehicle throttle value.

Thanks,

**Comment by E66666666** [comment]
There's no v1.2.3.1. The current build is v1.0.1290.1, or 1.42 (GTA:O). Everything should still work fine, I updated the offsets and patterns a day ago or something.

**Comment by n-akram** [comment]
hey man,

Thanks for quick reply. And I just saw that. I will update it. 

thanks,

**Comment by n-akram** [comment]
Hi,

I am using v1.0.1290.1. I actually saw some other version and said v1.2.3.1. 

The last version of GTAVManualTransmission which I used was 4.3.8. And I am trying to use the updated 4.5.1 version.

Anyways, I updated the source code. Only some files were changed, i updated them. I have used following libraries in my project.

VehicleData.cpp
VehicleData.hpp
VehicleExtensions.cpp
VehicleExtensions.hpp
Logger.cpp
Logger.hpp
NativeMemory.hpp
Versions.h
Offsets.hpp
MathExt.h

In earlier version, there was variable in vehicleData "Throttle" which was updated by calling updatevalues(ext,veh). This would use GetThrottle(vehicle) from VehicleExtensions.Cpp.

However, I noticed that these variables were removed in recent version. So i tried adding them and then using same function to update. This always returns 0.

Even RPM varaible, which I would expect returns the current engine RPM, just returns 0 (this is still there in this version).

My guess is that memory patcher does not work. 

Can you help me figure out what I am missing?

thanks a lot,

**Comment by E66666666** [comment]
You need to call VehicleExtensions::initOffsets to find the patterns, before using anything out of it.

**Comment by n-akram** [comment]
Thanks a lot dude. It is working now.
