### ISSUE TITLE
[FiveM] Brake not working

### ISSUE THREAD

**Issue by Nexendia-** [E66666666/GTAVManualTransmission#27]
Not sure what is triggering it but starting today after playing for a bit I have noticed I lose all brake functionality while going over 30mph nothing short of restarting fivem seems to fix it

Using a Thrustmaster T150 wheel & pedals if that helps.

**Comment by Nexendia-** [comment]
Engine braking was my problem setting it below a certain point only let the brakes work when it hit a low enough rpm

**Comment by E66666666** [comment]
What version are you using? I might need to fix it.
