### ISSUE TITLE
Decorator issue

### ISSUE THREAD

**Issue by brad2192** [E66666666/GTAVManualTransmission#3]
Greetings!
 I am really hoping you can help me out with this issue. I am using a mod called "FiveReborn" for multiplayer and from what I am being told they use ragehook and for some reason it is not playing nicely with "decorators" I have little experience with compiling and am wondering if you could help me out, I simply hate playing the game without your wheel support since I got it! Any info would help thanks again! P.S. I have tried using beta versions of your mod without the "decorator" and this is the [pic of error here](http://imgur.com/PRxjorH) and the 3.0.2 release say the same except Gears.asi+D535.

**Comment by brad2192** [comment]
I actually just read your new line in readme, is it possible you could make it work somehow? I know they released an API for it to be written in. I am really hoping you could do this for me you're my last hope :\

**Comment by brad2192** [comment]
I also know Lua scripts are pretty much the only thing they allow is it possible to recode this to Lua? Again I suck I do not know how :(

**Comment by E66666666** [comment]
Yes, I'm aware of this error. I can temporarily add a build without decorators. It should be in the releases page shortly.

**Comment by brad2192** [comment]
you're amazing, thank you so much!

**Comment by E66666666** [comment]
I've uploaded the changes. Due to circumstances I can't test with my wheel. If it's fixed, please let me know.

**Comment by brad2192** [comment]
Awesome, so this can be used with FiveReborn? and does it require additional dependencies other than the ones provided by FiveReborn? I will get back to you shortly!

**Comment by E66666666** [comment]
It should just work with FiveReborn, last time I tried it, it worked. I haven't made any changes since then.

**Comment by brad2192** [comment]
Alright, I am trying to "Build Solution" but I am getting error "Error	D8016	'/ZI' and '/GL' command-line options are incompatible	Gears	C:\Users\Brad\Desktop\GTAVManualTransmission-master\Gears\cl	1	" I honestly have little knowledge on how to do this. Is it possible you can update the file on GTA5-MODS?

**Comment by E66666666** [comment]
No, GTA5-Mods.com only gets relatively stable updates :P 

[Here](https://github.com/E66666666/GTAVManualTransmission/releases/tag/v3.0.2-cfx) is the .asi, precompiled.

**Comment by brad2192** [comment]
Sorry for being "that guy." I've spent the past week up until 5AM trying to learn as best I can, I will get back to you shortly if it works. If you know which directory I should have ScriptHookVDotNet in that would help quite a bit as well! My directory is as follows

C:\GTA V\
C:\GTA V\FiveReborn\
C:\GTA V\FiveReborn\plugins\*ScriptHookVDotNet[.asi,.dll,.ini,.xml]*
C:\GTA V\FiveReborn\plugins\scripts\*gears.asi*

Does that look correct to you?

**Comment by E66666666** [comment]
I had it
FiveReborn\plugins\Gears.asi
GTA V\Gears.ini

**Comment by brad2192** [comment]
It works! I honestly cannot thank you enough, you're awesome for throwing in quite a bit of extra effort to help a complete stranger out. I owe you, if there's anything I can do let me know, seriously. Thanks again man!

**Comment by E66666666** [comment]
That's all, thanks for letting me know! I'll shortly start working again on the mod after I've finished IRL stuff, and updated SlamIt for this new version.
