### ISSUE TITLE
Logitech Driving Force Pro - Accelerator is on/off, not analog

### ISSUE THREAD

**Issue by ascii-soup** [E66666666/GTAVManualTransmission#30]
Not sure if this is a bug or if I've done something wrong, but the accelerator is simply on/off - it doesn't matter how hard I press the pedal, it always accelerates to max. Is there a setting for this somewhere?

settings_wheel:
https://pastebin.com/GPSUDrLR

settings_general:
https://pastebin.com/q2EgphLr

**Comment by E66666666** [comment]
The settings look correct. What does Windows report for how the pedals behave?

You might also want to turn on the wheel HUD elements and debug display to see if the values indeed instantly go from 0.0 to 1.0, or some intermediate steps can be seen.

**Comment by ascii-soup** [comment]
I figured it out - the wheel was configured to report the accel/brake as a combined axis. I turned this off (involving getting old Logitech software) and it works a dream.
