### ISSUE TITLE
Steering gamma?

### ISSUE THREAD

**Issue by Luc45** [E66666666/GTAVManualTransmission#31]
Hi!

First of all, great mod, thanks for that.

I'm having some trouble with the steering, as it's very sensible to the tiniest movement. I didn't want to deadzone it as I would like to be able to make smooth turns.

 I've seen brake gamma, it would be awesome if there was a steering gamma.

Thanks

**Comment by E66666666** [comment]
Steering is staying linear for now. Have you tried dialing in the steering wheel angles to match your driver settings?

**Comment by E66666666** [comment]
@Luc45 
I'm closing this issue since it's not really a problem.

**Comment by E66666666** [comment]
@Vahinkolaukausosuma 
Late update: I implemented steering gamma in 14e0a1fc183ae3072e1158e4a66917f402ad4fb4.
