### ISSUE TITLE
Could it use Alternate Button on keyboard?

### ISSUE THREAD

**Issue by sinxhack** [E66666666/GTAVManualTransmission#32]
hello, this mod could use alternate button such as im set the button LSHIFT for shifting gear up and at the same time i want set the RHIFT to shifting gear up to. Thanks

**Comment by E66666666** [comment]
Yes, [it treats left and right modifiers as separate keys](https://github.com/E66666666/GTAVManualTransmission/blob/master/Gears/Input/keyboard.cpp). You can not assign two keys to do the same thing, however.
