### ISSUE TITLE
Brake does not works on Xbox 360 controller

### ISSUE THREAD

**Issue by ViacheslavRud** [E66666666/GTAVManualTransmission#35]
When I push left trigger it brakes and accelerates in same time in any gear, except R. In Rear gear it's impossible to brake, it accelerates with both triggers.
Game version is 1.0.1604.1
Gears-v4.6.5-Release
Reproduces on Auto and Sequential gearboxes.
Keyboard works fine.

**Comment by E66666666** [comment]
What vehicle does this happen with, and can you show me your `settings_general.ini`?

**Comment by ViacheslavRud** [comment]
> What vehicle does this happen with, and can you show me your `settings_general.ini`?

With any car.

settings_general.ini:

; Manual Transmission for GTA V
; Please refer to the readme or the in-game menu for option descriptions
; Please use the in-game menu to configure the mod


[OPTIONS]
Enable = false
ShiftMode = 2
SimpleBike = false
EngineDamage = false
EngineStalling = true
EngineStallingS = false
EngineBraking = true
EngineLocking = false
ClutchCatching = true
ClutchShiftingH = false
ClutchShiftingS = false
DefaultNeutral = false
ClutchCatchpoint = 10.000000
StallingThreshold = 85.000000
RPMDamage = 15.000001
MisshiftDamage = 10.000000
EngBrakePower = 0.800000
EngBrakeThreshold = 0.750000
HillBrakeWorkaround = false
AutoGear1 = false
AutoLookBack = false
ThrottleStart = true
CrossScript = true
HidePlayerInFPV = false
HardLimiter = false


[HUD]
EnableHUD = true
AlwaysHUD = false
HUDFont = 4
GearIndicator = true
GearXpos = 0.952500
GearYpos = 0.885000
GearSize = 0.700000
GearTopColorR = 255
GearTopColorG = 63
GearTopColorB = 63
ShiftModeIndicator = true
ShiftModeXpos = 0.935000
ShiftModeYpos = 0.885000
ShiftModeSize = 0.700000

; kph - mph - ms - off
Speedo = kph
SpeedoShowUnit = true
SpeedoXpos = 0.860000
SpeedoYpos = 0.885000
SpeedoSize = 0.700000
EnableRPMIndicator = true
RPMIndicatorXpos = 0.120001
RPMIndicatorYpos = 0.765000
RPMIndicatorWidth = 0.140000
RPMIndicatorHeight = 0.005000
RPMIndicatorRedline = 0.845000
RPMIndicatorBackgroundR = 0
RPMIndicatorBackgroundG = 0
RPMIndicatorBackgroundB = 0
RPMIndicatorBackgroundA = 128
RPMIndicatorForegroundR = 255
RPMIndicatorForegroundG = 255
RPMIndicatorForegroundB = 255
RPMIndicatorForegroundA = 255
RPMIndicatorRedlineR = 255
RPMIndicatorRedlineG = 92
RPMIndicatorRedlineB = 0
RPMIndicatorRedlineA = 255
RPMIndicatorRevlimitR = 255
RPMIndicatorRevlimitG = 0
RPMIndicatorRevlimitB = 0
RPMIndicatorRevlimitA = 255
SteeringWheelInfo = true
AlwaysSteeringWheelInfo = false
SteeringWheelTextureX = 0.230000
SteeringWheelTextureY = 0.890000
SteeringWheelTextureSz = 0.060000
PedalInfoX = 0.290000
PedalInfoY = 0.890000
PedalInfoH = 0.100000
PedalInfoW = 0.040000
PedalInfoPadX = 0.000000
PedalInfoPadY = 0.000000


[CONTROLLER]
ToggleEngine = false
ToggleTime = 300
TriggerValue = 0.850000
BlockCarControls = true
MaxTapTime = 200
ShiftUpBlocks = 73
ShiftDownBlocks = 99
Toggle = UNKNOWN
ToggleShift = B
ShiftUp = A
ShiftDown = X
Clutch = LeftThumbUp
Engine = DpadDown
Throttle = RightTrigger
Brake = UNKNOWN
IgnoreShiftsUI = false
BlockHShift = true
ClutchBlocks = -1


[CONTROLLER_LEGACY]
Enable = false
ShiftUpBlocks = 73
ShiftDownBlocks = 99
Toggle = -1
ToggleShift = 194
ShiftUp = 191
ShiftDown = 193
Clutch = 196
Engine = 187
Throttle = 208
Brake = 207
ClutchBlocks = -1


[KEYBOARD]
Toggle = VK_OEM_5
ToggleH = VK_OEM_6
ShiftUp = LSHIFT
ShiftDown = LCTRL
Clutch = Z
Engine = X
Throttle = W
Brake = S
HR = NUM0
H1 = NUM1
H2 = NUM2
H3 = NUM3
H4 = NUM4
H5 = NUM5
H6 = NUM6
H7 = NUM7
HN = NUM9


[DEBUG]
DisplayInfo = false
DisplayWheelInfo = false
DisplayGearingInfo = false
DisplayFFBInfo = false
DisplayNPCInfo = false

**Comment by E66666666** [comment]
`Brake = UNKNOWN`
There's your problem. Change it back to LeftTrigger

**Comment by ViacheslavRud** [comment]
Thanks it fixed issue! It was probably changed by mistake.
