### ISSUE TITLE
Mouse steering now does not work

### ISSUE THREAD

**Issue by SaggyBlackSack** [E66666666/GTAVManualTransmission#40]
When using the mouse as a steering wheel, mouse1 is now required to be held down. In other words, the R* feature "Default vehicle driving control - Camera" is now broken. 

And just to confirm this is tested across this version on the newest game, and override mouse control key bind settings has been checked.

This is 100% a MT issue

Cheers!

**Comment by SaggyBlackSack** [comment]
Oops sorry I need to clarify something, I am talking about being outside of first person. When using the regular third person camera and driving, simply moving the mouse no longer works as mouse steer even with Default mouse driving control set as camera. It now only works in first person.

Thanks again, and my bad,,,

**Comment by E66666666** [comment]
In don't think I touched the steering code in Default mode, but I'll re-check.

I tried to implement mouse support for the custom steering mode, but dropped it after I couldn't get it to work properly (plus it doesn't make much sense when your mouse isn't moving but the wheel is). It's been dropped ever since commit https://github.com/E66666666/GTAVManualTransmission/commit/4e01fc26c7c14d92a5f6575f5227ed603498ec5f. If you've got some suggestions, feel free to post them.

**Comment by SaggyBlackSack** [comment]
Ikt, every time you reply it is so confusing. Mouse steering does work in custom steering mode, I didn't say it did not. Please read my issue, as it is a breaking aspect of your mod.

I control my vehicle via my mouse, both in and out of third person. THIS version of this mod, not the last version but this version only, has broken the OUT of first person mouse steering control IF the player has "default drive control - camera" selected in the game's options.

My issue IS NOT related to the new custom mouse steering mode, which I am not using for the simple reason that is resets the car's visual model steering wheel dispite having InfamouseSabre's ACS and using Enhanced Trainer's option. If this still does not make sense to you:

When pulling up and getting out of a car with the new steering mode enabled, the steering wheel snaps to 12o'clock. 

Bug #2: when moving the mouse (without holding down MOUSE1 or any other mouse button), outside of third person it does NOT STEER. Please please fix. PLEASE FIX. Do you understand this is NOT a custom steering mode bug? This is an OUT OF THIRD PERSON MOUSE DRIVING FAULT.

Bug numbro uno das: No sfx from shifts to and from 1st. PLEASE add the sound files (OR FILE THAT WOULD DO) called INTERNAL_GEAR_SHIFT.wav inside of vehicles.awc

Thank you.

**Comment by E66666666** [comment]
Okay, I sense some frustration here, but you seem to have issue getting your point across.

In the future, please include the following information when reporting something. I'll make an issue template so this is clearer for people who want to report an issue or request a feature in the future.

* What *release* are you using?
  * If using the automatic AppVeyor builds, please mention commit. I'll add release information to the log/.dll in the future.
* What *mod* settings are you using?
  * Mentioning the relevant settings is fine, but in doubt, feel free to attach the settings files.
* What (relevant) game settings are used?
  * This you already included in your original report.

Now onto the issue(s):

> Mouse steering does work in custom steering mode

Mouse steering should be broken/disabled entirely in `Steering Mode` set to `Enhanced`. 

> My issue IS NOT related to the new custom mouse steering mode

This fairly important detail you might have wanted to mention somewhere.

Regardless - I just tested both scenarios, and none of what you mention happens. (Default) Mouse steering still works in Default mode, and does not work in Enhanced mode. 

> resets the car's visual model steering wheel dispite having InfamouseSabre's ACS and using Enhanced Trainer's option. If this still does not make sense to you:
>
> When pulling up and getting out of a car with the new steering mode enabled, the steering wheel snaps to 12o'clock.

I can not reproduce this. With ACSPatch the wheels stay where they are pointing when getting out when using a steering wheel, keyboard, gamepad or mouse steering.

> No sfx from shifts to and from 1st. PLEASE add the sound files (OR FILE THAT WOULD DO) called INTERNAL_GEAR_SHIFT.wav inside of vehicles.awc

That's on the to-do-list, then.

Here's my attempts at reproducing the issues you report:
https://www.youtube.com/watch?v=9v2IiQv7tr0

All steering input you see while Steering Mode was set to Enhanced is from the keyboard.

**Comment by SaggyBlackSack** [comment]
Sorry for the delay I will add a reply that you will appreciate tomorrow

**Comment by SaggyBlackSack** [comment]
For the time being, please download my mod https://www.lcpdfr.com/files/file/21519-scan-superior-siren/ and see that internal gear shifts are infact the only way in which first person players hear any shifting sounds which are defined under the audio set used in vehicles.meta. Do you really not care that the first gear shift is silent? I don't get this nwo way of thinking. It's literally the last thing to polish this script so it's completely amazing. Internal_ gear wavs do exists, there's 4 of them and 5 external. These are inside of vehicles.awc. See here please:

![image](https://user-images.githubusercontent.com/26041830/66223181-c4243400-e6ca-11e9-9817-fcb6a6e092fd.png)

Can you _please_ add this small polish. It would mean a lot to me and all my future times playing this game. It is just a sound file. A tiny line of code could sound this file on shifts down to or up to 1.

**Comment by E66666666** [comment]
If you could just point out what "tiny little line of code" should do this, be my guest.

I've dug through a bunch of calls to play sounds and it seems like there isn't a simple mapping from awc archives/individual sounds to whatever the scripts use, with `PLAY_SOUND_FROM_ENTITY` for example.

Be aware that `PLAY_SOUND_FROM_ENTITY` needs an `audioName` and `audioRef` or rather, soundset. The latter *can* be left empty but it depends on where/how the sounds are defined. I've looked for some dumps of playable sounds but didn't find anything like internal/external gear change sounds.

Let me reiterate that I am not willing to drag in a third-party library to play sounds. If however you do find a **script-playable** sound, I'm more than willing to add *that*.
