### ISSUE TITLE
Enhanced Steering is *mwha*

### ISSUE THREAD

**Issue by SaggyBlackSack** [E66666666/GTAVManualTransmission#42]
Hello, I'm sorry and I know you hate me for creating this page on your github which you work hard on, I'm sorry but I really want to recommend something and this is the only way I can.

Your programming is great and you're clearly a very clever person who knows how to write mods like this, which is something I wouldn't event begin to comprehend. I would really like to put forward two suggestions

Okay, so the new enhanced steering system is great, it works in a whole different way with BetterVehicleFirstPerson than you think, and I really enjoy the idea of the steering multiplier (let's just call it steering reaction from now on) getting higher as speed increases. But I would like to suppose a completely opposite system where we still have the bottom-option of steering multiplier, but a new system, possibly in the slide menu as normal/ default and enhanced is now, but this one is for going down in steering reaction. 

I would LOVE this system, can imagine it so well. So, I as a player would have my steering multiplier on say 0.04 (for my 1965 truck with oil hauling), if you could please please add an option to START at 0.04 (or any other number) and work our way down based on speed? For example, the ways I would use this are:

Sports cars are usually on 0.11 - 0.15 for me, so I would like it if at climbing speed I go from 0.15 to 0.04 as to create co-efficient drag. I love doing this already with my steering reaction trick, but this way would offer a lot too! Okay, that's one out the way :P

Once again I'd like to suggest another steering system, this one would be the big daddy for me. The variable super mod hehe..

At the moment, my steering multiplier is something I change CONSTANTLY in game, I really like 0.02 and 0.04 for old trucks, and then I use 0.15 to 0.19 for ambulances, coupes etc. Could you by any chance introduce *another* steering system with this being the premise:

I set 3 variables. Starting steering reaction (multiplier), crawl multiplier and flat out multiplier. I use the keyboard to apply throttle using 1 TO 5, and I also use W for when I am just chilling. This system would allow us players to be at motorway speeds and have a steering reaction of 0.15, but when we pull off the road onto a gravel path and create plumes of dust and smoke, the mod will blend the steering wheel reaction to 0.04 so the wheels make small amounts of angle change on low speeds. Please man, I know this sounds heavy but as 1 human to another. (By the way I do work with computers, but not at all like game design or programming like yourself) but can I just say to you hand on heart... I think this would be easy as pie. It sounds complex but it is all there already. You have already created the blend-thingy for the enhanced steering system to step up the steering wheel on higher speeds, please add a small medium large fries mode too! Lol. Please think about my ideas. Ps Reverse causes all engine types to stall currently. 

Can't thank you enough. I'll paypal you £50 bones near Christmas thank you so much for ManualTransmission   

PPs feel free to obviously delete this text from your github page I just want you to read it I don't care about other people or being public. I just really really want this mod to get even better, not that it isn't all ready mind blowingly immersive!!!

-Callum

**Comment by E66666666** [comment]
Creating issues is fine.

> Decreasing steering multiplier at speed

The steering reduction at speed is already present, as tries to emulate the default game behaviour. The code for that is found [here](https://github.com/E66666666/GTAVManualTransmission/blob/000dc5dd464f7a9868f68a089ff389dc3df4f92b/Gears/CustomSteering.cpp).

Steering multiplier was never intended to be changed on-the-fly. I don't know in which context your description of changing the steering multiplier is. Is this still with the steering angle tweak, in order to have the steering wheel turn more, visually?

**Comment by SaggyBlackSack** [comment]
> Is this still with the steering angle tweak, in order to have the steering wheel turn more, visually?

It's not about visuals at all. I would just really appreciate and enjoy it if there was a system I could choose to enable, like switching steering mode under mouse / keyboard, in where it would start with a base amount, get to a middle amount, and then a max amount. So it could be really simple and say, from absolutely stopped 0 miles per hour, to 10 is base, crusing the roads from 10 to 30 in game units MPH, and then finally highway amount.

I have thought about this a lot. I really like the way enhanced steering works at the moment, but I can't use it cos of the mouse-steering incompatiblity. Not saying that's my issue lol, but I do like it. I would love it reversed, so at low speeds the steering multiplier is 0.04 (or whatever), and then a second option (or third like I say), for "Steering multiplier to reach", and then the first one would be the "starting" multiplier. That way it would be realistic, because currently the first person all these millions of youtube videos have and stuff is gta V r* bog standard, which is diSGUSTING, sound fx changing, timecycle modifing, fucking horrible camera they invented. BetterVehicleFirstPerson is the only way anyone should ever play gta V as a driving sim / chillout driver.

You can't say you won't design in mind for that mod, becaues it doesn't make any difference. You haven't in the passed, I don't think, and this mod is amazing. I love it, I really love this mod it feels amazing to drive with this and BVFP, so if there's anyway you can create a basic system that has a starting steering angle multiplier, setable by us, and a goal/reach multiplier achieved via speed climbing. Mwha perfecto, just like the current enhanced system but reversed. More realistic because the value differnece (or at least feel) in the enhanced system for me is extremely sensitve. I mean litterally corners need like 1cm of rl hand movement to mouse steer it's horrible. Not saying that needs to be fixed, I just want my own system... and for everyone to see how amazing gta V can be, but I am the only person talking about this "amazing experience" Well trust me, I can't record it but it is amazing.

Peaceeeee till next timmmmme

**Comment by SaggyBlackSack** [comment]
I read through all that code, why did you have me do that? 

I like level design, not programming. :D

**Comment by E66666666** [comment]
No clue what you're on about. 

> where it would start with a base amount, get to a middle amount, and then a max amount.

* Define "it".
* What does "amount" refer to?

>so at low speeds the steering multiplier is 0.04 [...]

So in effect you want to move your mouse *less* when stopped, and *more* to reach the same steering lock when at a certain speed? There's no system where such a reverse gamma makes sense.

**Comment by SaggyBlackSack** [comment]
It = steering multiplier
Amount = steering multiplier.

I don't want a complex system or anything. but you see how you've got the enhanced system now? I want that but less harsh, and without the mouse steering bugs. I don't want anything except for this: At low speeds steering multiplier is base value I set, and my vehicle CLIMBS to reach a MAX steering angle input value.

PLEASE (and the SFX for gear 1, then you'll never hear from me again and I can donate 20 or 30 bucks to say thanks!!

**Comment by SaggyBlackSack** [comment]
I just had a great session of driving around listening to a podcast for a while and I really can't beg for a mouse-steering working version of the ehanced steering system enough. Lol

I love it, it just increases too much for me I want control over the increase, maximum and minimum gamma changes. I also want the wheel to stay angled properly with mouse steering. Christmas can still come early.

Oh,
And just 1 more thing mr claus, the SFX is missing for gear switches to and from first. Not sure if you was aware 🤓

**Comment by SaggyBlackSack** [comment]
https://www.youtube.com/watch?v=gZgJWX96dVQ
