### ISSUE TITLE
Adaptive braking

### ISSUE THREAD

**Issue by SaggyBlackSack** [E66666666/GTAVManualTransmission#44]
_Hey, delete other thread if ye wish. It was not formulated properly._

I have a very concise and I believe desired feature idea about braking.

Currently when braking, the value of BrakeForce is the amount of that brake. Whereas some scripts exist that apply both brake and throttle in a more "gradual" amount, such as TractionControl in ENT, my idea works via 2 amounts the player sets.  

The lowest brake possible, and the highest amount possible. I imagine this as field or slider data type. The purpose is to use the lower brake amount when the car is under 15 feet a second, or going very slowly as to pull up or park. The high amount is the regular amount. And will apply at all other times, or instead we just introduce a lowest brake value instead of the two. The system will still work accordingly, but with the use of the vehicles handling default value already got. 

I use this system already, and have done for about 4 months. Every single vehicle I use has a BrakeForce value of 0.04 to 0.08. I really like these values for literally everything, cars, trucks. Of course there is a tiny, tiny learning curve required to enjoy this low brake amount. I can compare it to people that play Gran Turismo and just flat out accelerate and then crash and say the car has "no handling". GTA V does absolutley not have any handling. Car's just say oh you wanna stop BOOM stopped.

This system would be lovely as it would let me start braking in emergencie situations again. I've had to, for now, bind my brake to handbrake, and S became my Q, and Q is toggled via Ent hotkeys, so I can get out and the handbrake still stays on. When I'm pulling up to a sidebay very fast I put the brake on and I also judge it really well, it's like a game of calculations in your mind whilst playing. I would really enjoy 2 brake values, one for cruising, parking, stopping, and 1 for driving fast and needing to stop in a dime (Which some cars do in real life). 

Thanks Ikt

**Comment by E66666666** [comment]
What you're describing is input modulation. Please just use a controller, I'm not going to modulate user input in this script.

The biggest issue that would arise from supporting this is I'd have to re-do *everything* input-related in the script.

**Comment by SaggyBlackSack** [comment]
Wow you're rude.



### **Just add the fucking SFX for all the gears you lazy prick**

**Comment by SaggyBlackSack** [comment]
hahahah Ill have 1 hand on my mouse and 1 on the left hand sideo f a controller yeah oki doke aspergers, peace

**Comment by SaggyBlackSack** [comment]
Seriously how dumb can you pretend to be. "iNPUT mODulation" na it's called a 4 line script according to enhanced trainer which has had traction control (Which pumps 50% brakes on first 1 second and then 100% on the rest) since 2018 ahaha input modulaiton okay nasa 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓

**Comment by SaggyBlackSack** [comment]
What's invalid?

**Comment by SaggyBlackSack** [comment]
Your understanding
