### ISSUE TITLE
[BUG] Seventh gear worse than sixth

### ISSUE THREAD

**Issue by andradadad** [E66666666/GTAVManualTransmission#52]
**Describe the bug**
Buying the transmission repair and adquiring a new clutch to the car, in really high speeds as 190km/h, when the sixth gear is at maximum, shifting to the last gear reduces speed.
 
**To Reproduce**
1- Buy transmission
2- accelarate and shift to 7 gear 

**Expected behavior**
The car moves to 210km/h or makes the acceleration better, not worse.

**Screenshots and/or videos**
If applicable, add screenshots or video to help explain your problem.

**Used versions and additional hardware:**
 - Game version: [e.g. 1.0.1337.1 on Steam)
 - Mod version: [e.g. v4.6.7, AppVeyor build]
 - Additional hardware: [e.g. Logitech G29, Xbox One controller]

**Settings, if applicable:**
 - If applicable, link to settings_general.ini
 - If applicable, link to settings_wheel.ini

**Additional context**

**Comment by E66666666** [comment]
@andradadad 
Yeah, this is a known problem. Rockstar somehow made the gear ratio table stop at 6, and the 7th gear is always with a ratio of a lower gear.

I did make a fix/solution for this, with the [Custom Gear Ratios](https://www.gta5-mods.com/scripts/custom-gear-ratios) script, which works great. It's not very visible though so I'm curious to hear why you hadn't stumbled upon the gear ratio script and what I could do to improve its visibility (e.g, should I include it in the manual transmission script as a link or something?)

**Comment by andradadad** [comment]
Tried running custom gear ratios with last manual build and it showed "vcruntime1_40.dll" is missing.
It's the last manual transmission showing that.

**Comment by E66666666** [comment]
@andradadad 
That's *probably* CGR? Not sure.

Try installing https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by andradadad** [comment]
Already have that. Downgraded to 4.6.7

**Comment by E66666666** [comment]
Anyway - this isn't really an issue with the script, and [CGR](https://github.com/E66666666/GTAVCustomGearRatios) already fixes it. Closing this issue.
