### ISSUE TITLE
I can't configure any wheel buttons (only steering, brake, throttle)

### ISSUE THREAD

**Issue by Gonzaxpain** [E66666666/GTAVManualTransmission#54]
Hi everyone, I downloaded the latest version of the mod last week in order to play this along with LukeRoss's VR mod for GTAV. Everything is working great but for some reason this mod won't recognise any wheel buttons. Steering, throttling and braking work great but nothing else.

 I'd like to rebind the 'look behind' , 'get out the car' and other stuff to my wheel buttons but they're not recognised (Xbox pad does work and allows rebinding). I tried both the in-menu game and the exe inside the install folder which does recognise the input but won't save them. 

Any help on this? Any way to make the buttons on my wheel (Thrusmaster T150) recognised? It's not a big deal as I am enjoying both mods immensely even if I have to use the gamepad for certain functions but I'd like to make it even better.

Thanks!

**Comment by E66666666** [comment]
The buttons *should* just work. What submenu are you using to assign buttons?

Also please attach `Gears.log` and `settings_wheel.ini`.

**Comment by Gonzaxpain** [comment]
Sorry, I was at work. Find enclosed the logs.

I am using the in-game menu via RButton+Circle, then steering wheel>Button Input setup

Thanks!

[gear+wheel.zip](https://github.com/E66666666/GTAVManualTransmission/files/4192694/gear%2Bwheel.zip)

**Comment by E66666666** [comment]
Whoops, late reply.

You could try to manually insert the keys, but it's a mystery to me why it apparently only recognizes a few things. `Steering Wheel`->`Button Input` is the correct path afaik...

**Comment by Gonzaxpain** [comment]
Don't worry, it was more out of curiosity than necessity, I'm almost 30 hours into the game by now and it's not much of a problem to have to grab the controller for certain actions, driving works great and that's what matters.

**Comment by E66666666** [comment]
Still odd, but I'll close the issue since it doesn't appear like there's anything the mod does causing this behavior.
