### ISSUE TITLE
[BUG] Engine start/stop button timing issues

### ISSUE THREAD

**Issue by csendo2** [E66666666/GTAVManualTransmission#57]
Hi!
In the mod, there's an option which allows us to not only restart a car after stalling, but also turn it off while it's running. I've experienced an issue with this feature while using a controller.
My engine button is assigned to A, and restarting after a stall works fine. However, when I'm trying to shut the engine, there's only a really small window in which it works. If I hold it for just a bit longer than this window, it'll immediately restart the engine. I know there's an option to edit some millisecond time values in the menu, but tinkering around with those numbers did seemingly nothing.
It's not a huge issue, the mod is still awesome, I just thought I'd leave it here.

**Comment by E66666666** [comment]
Thanks for the report! You're right, I checked for if the button was held over some timeout, while I should've checked if it's released after that time.
