### ISSUE TITLE
Not Needing Clutch To Shift

### ISSUE THREAD

**Issue by Mnky313** [E66666666/GTAVManualTransmission#6]
I have ClutchCatching and ClutchShifting set to 1 and I can still shift gears (except from N-1) without using clutch. Anyone know why?

**Comment by Mnky313** [comment]
[OPTIONS]
Enable          = 1
ShiftMode       = 0

SimpleBike      = 0

EngineDamage    = 1
EngineStalling  = 1
EngineBraking   = 1
ClutchCatching  = 1
ClutchShifting  = 1
ClutchShiftingS = 1
DefaultNeutral  = 1

ClutchCatchpoint = 15
StallingThreshold = 75
RPMDamage = 25
MisshiftDamage = 5

; At default GTA V applies brakes when standing still, while even
; at an angle. Enabling this will give your car a little push.
; Thanks to XMOD!
HillBrakeWorkaround = 1
AutoGear1 = 0
AutoLookBack = 0

UITips      = 1
UITips_X    = 95
UITips_Y    = 90
UITips_Size = 150
UITips_OnlyNeutral = 0
UITips_TopGearC_R  = 255
UITips_TopGearC_G  = 127
UITips_TopGearC_B  = 127

CrossScript = 0

That Is The Options Part Of The Gears.ini file

**Comment by E66666666** [comment]
Keyboard, controller or wheel?
H-shifter or sequential?
What version of the mod?

**Comment by E66666666** [comment]
@Mnky313 Please respond, I can't replicate this. Will close somewhere during this week.
