### ISSUE TITLE
[BUG] New added memory pattern 'ThrottleLift' arent worked in version 1180

### ISSUE THREAD

**Issue by Nyconing** [E66666666/GTAVManualTransmission#70]
Im happy to help to find correct pattern in my 1180, but I dont know how to do it.

The log file as below:

> [20:00:25.298] [ INFO  ] Manual Transmission v4.7.2 (built Apr 30 2020 16:31:16)
> [20:00:25.303] [ INFO  ] Game version VER_1_0_1180_2_STEAM
> [20:00:25.308] [ INFO  ] Running executable: Q:\Space\Game\GTAV\Grand Theft Auto V\GTA5.exe
> [20:00:25.314] [ INFO  ] File Version: 1.0.1180.2
> [20:00:25.328] [ INFO  ] Script registered
> [20:01:21.959] [ INFO  ] Script started
> [20:01:21.997] [ INFO  ] [Settings] Timers: Stopped after 0 timers
> [20:01:22.002] [ INFO  ] Settings read
> [20:01:22.007] [ INFO  ] Configs loaded: 0
> [20:01:22.223] [WARNING] Hover Transform Active Offset: 0x0
> [20:01:22.228] [WARNING] Hover Transform Ratio Offset: 0x0
> [20:01:22.809] [ ERROR ] [Patch] Test: [Gears: Throttle lift] not found
> [20:01:22.911] [ ERROR ] Patchability test failed!
> [20:01:22.917] [ INFO  ] Setting up TrainerV compatibility
> [20:01:22.922] [ INFO  ] TrainerV.asi not found
> [20:01:22.927] [ INFO  ] Setting up DashHook compatibility
> [20:01:22.933] [ INFO  ] DashHook.dll not found running, loading...
> [20:01:22.940] [ INFO  ] DashHook.dll load failed, error [126]
> [20:01:22.945] [ INFO  ] [Wheel] Initializing input devices
> [20:01:22.950] [ INFO  ] [Wheel] Setting up DirectInput interface
> [20:01:23.002] [ INFO  ] [Wheel] Found 2 device(s)
> [20:01:23.007] [ INFO  ] [Wheel]     Name:   Controller (XBOX 360 For Windows)
> [20:01:23.013] [ INFO  ] [Wheel]     GUID:   {DF184250-8941-11EA-8001-444553540000}
> [20:01:23.019] [ INFO  ] [Wheel]     Name:   Wireless Controller
> [20:01:23.023] [ INFO  ] [Wheel]     GUID:   {CC70ACB0-8940-11EA-8001-444553540000}
> [20:01:23.029] [ INFO  ] [Wheel] Devices initialized
> [20:01:23.034] [ INFO  ] [Wheel] Initializing force feedback
> [20:01:23.038] [WARNING] [Wheel] FFB device not found
> [20:01:23.043] [ INFO  ] [Wheel] Not set up in .ini: 
> [20:01:23.048] [ INFO  ] [Wheel] Device: Wireless Controller
> [20:01:23.053] [ INFO  ] [Wheel] GUID:   {CC70ACB0-8940-11EA-8001-444553540000}
> [20:01:23.058] [ INFO  ] [Wheel] Device: Controller (XBOX 360 For Windows)
> [20:01:23.064] [ INFO  ] [Wheel] GUID:   {DF184250-8941-11EA-8001-444553540000}
> [20:01:23.069] [ INFO  ] [Wheel] Steering wheel initialization finished
> [20:01:23.075] [ INFO  ] START: Initialization finished
> [20:01:23.080] [ INFO  ] [Telemetry] Starting UDP on 127.0.0.1:20777
> [20:01:32.012] [ INFO  ] Checking for updates
> [20:01:36.345] [ INFO  ] Configs loaded: 0
> [20:01:37.909] [ INFO  ] PATCH: Init shutdown
> [20:01:37.913] [ INFO  ] PATCH: Script shut down cleanly

**Comment by E66666666** [comment]
Check the comments:

```cpp
// When disabled, game doesn't lift throttle during shifts
// Also useful to set throttle in 2nd+ while in fakeNeutral/clutched in
```

I think I added it to keep the turbo spooled up during shifts when not lifting throttle. Since I do not have a 1180 backup, I can't fix this.

**Comment by Nyconing** [comment]
Do you want 1180 game? Or how can I provide to help to do this compatibility? Memory dump?

**Comment by E66666666** [comment]
So what I remember, is that I found this during testing my turbo script.

If you turn on debug mode, you can see Throttle on the left debug values. If you disengage the clutch in first gear, throttle changes values normally. If you disengage it in second gear, the throttle does not change and stays at `0.0`.

That is what it patches. You can use Cheat Engine and find the throttle value, check what's writing to it when it sticks at 0 while you're revving while holding the clutch in second gear (or higher).

It's a *very* specific use-case, but kind of important for the turbo script. (keep the turbo spooling while shifting)
