### ISSUE TITLE
[FEATURE] Play charger blow off sound and fire animation while shifting

### ISSUE THREAD

**Issue by Nyconing** [E66666666/GTAVManualTransmission#77]
**What does this feature relate to?**
visual feedback/realistic

**Describe the solution you'd like**
Play charger blow off sound and fire animation while shifting, If it can triggers controller vibrator even great

**Comment by Nyconing** [comment]
Just mention, not sure it was bug or not, the blow off sound and fire animation are only play at very high rev or throttle are release

**Comment by E66666666** [comment]
Hmm, I have no plans to play extra audio, since that means dragging in another (audio) library. I don't think we can force the specific thing anyway, I at least haven't found anything specific to it.
