### ISSUE TITLE
[FEATURE] engine stalling feedback

### ISSUE THREAD

**Issue by raegenhere** [E66666666/GTAVManualTransmission#78]
When I use manual H-pattern shifting with clutch, my engine is stalling a lot, even with well tuned and genrous settings for the clutch. Especially during hectic gameplay/crashes it's easy forget about it. Having the engine turn off during in a chase is bad enough, even worse if you don't realize it, since enige sounds are quite low and get drowned easily. Obviously practice makes it better, but instead I find myself avoiding H-pattern & clutch because of it. 

I feel like any kind of feedback would be immensly helpful, to get a feeling for the clutch, and to give a small chance to react or at least make you notice you screwed up. 

I think it would require a small RPM range (and/or time window?) before the engine shuts down (or is there already? Hard to tell). During that, the player could be informed in various ways:
1) visullay: warning on the HUD (maybe an engine icon, green for running, red flashing for stalling, grey for off, something like that)   
2) auditory: stalling sound, like with the misshift. Probably weird if it's the same on every car though, so might be hard to do.
3) haptic: force feedback effect on the wheel, simulating an unsteady engine shaking the car. Probalby not too realistic, been a while since I've been in a car IRL.... not sure, but could feel right for crude engines in oldschool cars, which are fitting for H-pattern. 
If the engine has died, a more pronounced lack of servo-assist (making the wheel a lot harder to turn, maybe dependant on vehicle mass) could be a good 'hint'.

**Comment by E66666666** [comment]
>I think it would require a small RPM range (and/or time window?) before the engine shuts down (or is there already? Hard to tell).

It's already there.

> 1. Visually: Warning on the HUD (maybe an engine icon, green for running, red flashing for stalling, grey for off, something like that)

Good idea, actually. Probably the battery icon might be useful, though I don't know what other lights are on during a stall. If you could find a video or something, would be neat.

Right now the RPM indicator going flat should also be decent enough info, though.

> 2. Auditory: stalling sound, like with the misshift. Probably weird if it's the same on every car though, so might be hard to do.

Don't think cars stall "noticable". Also I hate working on audio.

> 3. Haptic: force feedback effect on the wheel, simulating an unsteady engine shaking the car. Probalby not too realistic, been a while since I've been in a car IRL.... not sure, but could feel right for crude engines in oldschool cars, which are fitting for H-pattern.

Depending on the car it just dies, or if it's a diesel (and/or has plenty of torque) it might shake.

> If the engine has died, a more pronounced lack of servo-assist (making the wheel a lot harder to turn, maybe dependant on vehicle mass) could be a good 'hint'.

This already exists. The damper values are 2x higher when the engine is not running.

**Comment by raegenhere** [comment]
so I got to drive my roommates car and naturally I stalled it for further research :)

What was most noticable was before a stall the car accelerates a bit, something like the counterpart to engine braking (maybe to the same ground speed even?). And right while stalling, the car does like a little jump. I think both would be noticable on the wheel, depending on current steering position. Maybe the effect could be exaggerated for gameplay effect. 

The car did shake on low rpm (it's a BMW, running on petrol). Not too noticable on the wheel IRL on modern cars, still I think it might work for gameplay purposes. 

Concerning lights - my roommates car shows the yellow engine symbol right after a stall. No warning before the stall, probably unneccessary in a real car with all the other feedback.
https://imgur.com/a/HVyvVXK
Second picture is when I start the car, when all icons go on for a moment. Not necesseary by any means, but would be a nice touch for immerison. On failed engine starts, which are often hard to hear with all that chaos, ot might even be a bit helpful if this triggers reapeatly. 

For reference, this is how i've seen it done in another game, which triggered the idea to submit this feature suggestion:
https://i.ytimg.com/vi/I9c9Fai6QPw/maxresdefault.jpg
It's like a little countdown. Of course this wouldn't fit in with your mod or GTA in general. But it was extremely helpful to me makes me believe that some kind of warning/feedback is needed for playing with clutch.

**Comment by E66666666** [comment]
So on my to-do list for this:

- [ ] Add stalling parameters (stalling rate, stalling RPM/speeds)
- [ ] Add FFB shake when engine cuts off (collision?)
- [ ] Add FFB continuous shake when in stalling-rising condition (wave effect?)
- [ ] Dashboard christmas lights when stall-induced engine-off state

**Comment by E66666666** [comment]
No FFB when starting to stall, but the RPM bar indicates it now. (RPM value drops below idle, bar becomes red)

**Comment by raegenhere** [comment]
Thanks! Much better now! Actually noticing a stall definitlely helps with learning to avoid one
