### ISSUE TITLE
[FEATURE] indivual toggle buttons for ABS, TCS, ECS

### ISSUE THREAD

**Issue by raegenhere** [E66666666/GTAVManualTransmission#79]
like the title says, indivual toggle buttons for ABS, TCS, ECS would be great for those with buttons to spare on their hardware

**Comment by raegenhere** [comment]
while I am at it - a toggle for handbrake would be nice too!

**Comment by E66666666** [comment]
the handbrake thing is a bitch to add (properly)

**Comment by E66666666** [comment]
The handbrake thing is a decent idea, but a bitch to implement in my script. I don't see much demand for it, and [Eddlm's "GTAExtended - Gameplay"](https://www.gta5-mods.com/scripts/gtaextended-gameplay) already does exactly this. (pretty nicely too)

Feature request finished.

**Comment by raegenhere** [comment]
Thanks a lot! 

Handbrake toggle is of course no big deal at all, probably wouldn't even bother with the mod if not for other features ;)
