### ISSUE TITLE
[FEATURE] request for Cruise Control

### ISSUE THREAD

**Issue by dodgebo1213** [E66666666/GTAVManualTransmission#83]
Cruise Control

Cruise control / speed hold with a keybind

I've noticed in menyoo they have a cruise control which is just a speed hold ..
throttle doesn't turn it off its got to be done manually ... however i haven't 
found a way to bind it to a key.. i'm a beginner coder and don't have a whole lot of 
suggestions that would be helpful... its just a basic idea that i think would fit your mod beautiful
if its not too much of a pain in the neck. 

my original comment on 5mods was as follows... 
dodgeboy121
hey bro, i know you're probably getting tired of my suggestions but ive been trying to use cruise control mods for months and they seem to break my game or just dont work well or how i like them too work ... I wish manual transmissions had a build in cruise control feature .. even a basic keybind to freeze speed ... i know this is asking A LOT. hope you're well thanks again for this wonderful mod

Again thank you so much for hearing my comment and being willing to conceive this suggestion! you're the best! 

-Dodgeboy121

**Comment by E66666666** [comment]
I am **really** not very enthusiastic about implementing this idea. The idea is nice though. A quick list of stuff I'd need to do:

- [ ] Add a control to toggle cruise control
- [ ] Add controls or control overrides for cruise control adjustments
- [ ] Refactor wheel code to support script-driven cruise control
- [ ] Probably a bunch of cruise control settings

If someone is willing to help - sure, but I think I'll just ignore this feature request for the time being, and get the 4.8.0 release out.
