### ISSUE TITLE
[FEATURE] custom FPV camera origin

### ISSUE THREAD

**Issue by raegenhere** [E66666666/GTAVManualTransmission#88]
Loving the new custom FPV camera feature so far!
However, I find the camera postion, from which I base my FOV, height and forward offsets, to be a very inconstent across vehicles, compared to the vanilla first person camera. Once I find good settings (that aren't worse than the vanillla ones) for one car, the will be completely off in a different vehicle. For an extreme example, if I set heiht offset in order to get a decent view of the street for sports cars, I won't be able to see the the handlebar at all on a motorcycle.

SIt's of course probably more realistic if the view is worse in certain vehicle types, but I'd value playability and constitency here. It seems to me, that because of that, viewpoints for each vehicle. are manually set (Could be wrong of course, in which case my suggestions are obsolete).

So my suggestion would be - could the camera origin for the custom FPV camera and its effects be this defined viewpoint for each vehicle in vanilla, instead of the player characters head?  

Even more ideal would be to be able to set a "bias" between charceter model head and vanilla cockpit viewpoint, and modify FOV and offsets form there and enjoy the immersion of the effects

**Comment by E66666666** [comment]
That's too much work and other excellent camera scripts already exist:

* [Custom Camera V Plus](https://www.gta5-mods.com/scripts/custom-camera-v-plus)
* [Better Vehicle First Person](https://www.gta5-mods.com/scripts/better-vehicle-first-person)
* [Drive Modes](https://www.gta5-mods.com/scripts/drive-modes)

It's honestly just a workaround for the limited sideways rotation the default FPV camera is locked to when playing animations.

**Comment by E66666666** [comment]
Now I think of it - CVehicleModelInfo might contain the vehicles.meta-defined FPV offsets. I don't have any issues using that.

**Comment by E66666666** [comment]
Addressed in feaf600

**Comment by E66666666** [comment]
Actually this is giving more problems than not, so I'm cancelling the idea.
