### ISSUE TITLE
[FEATURE]Other Controls to Steering Wheel

### ISSUE THREAD

**Issue by jdawgzim** [E66666666/GTAVManualTransmission#93]
**What does this feature relate to?**
Mapping game controls to wheel.

**Describe the solution you'd like**
I would love to have a buttons on the wheel that lets me aim and fire my gun with my VR headset.  Other buttons could be useful too.

**Describe alternatives you've considered**
I guess I could figure a way to map keyboard buttons to my steering wheel.  I guess I could ignore the mods way of mapping and try to map all keyboard controls through the Logitech software.  Currently my Logitech software won't even identify that I have the G29 connected even though the games can see it.

**Comment by E66666666** [comment]
It's possible to map any key (including mouse buttons) to any wheel input.

There's no aiming though and that's out of scope. Since you use a VR headset, it should already have things to allow aiming with the VR controls.

**Comment by jdawgzim** [comment]
I've tried to map buttons using the mod's GUI.  I can map a few functions in there.  That GUI can't map anything else can it?  

When you say, "It's possible to map any key" what method/tool are you referring too?

**Comment by E66666666** [comment]
The "Wheel To Keyboard" thing.

**Comment by E66666666** [comment]
Bruh 2 years.

It's in the mod, in the steering wheel button assignment.
