### ISSUE TITLE
[FEATURE] disable camera autocenter

### ISSUE THREAD

**Issue by shinelucid** [E66666666/GTAVManualTransmission#94]
Relates to camera settings, features an extra toggleable option in misc options menu, no alternatives needed its simple enough as it is.
P.S: you sent me here to make this request so there it is i hope its an easy one to implement :)

**Comment by E66666666** [comment]
For what?

**Comment by E66666666** [comment]
Sorry, due to how controller look is programmed, I can't disable auto-center there.

For the mouse, it has its own auto-center timeout option. Just throw some ridiculous number in there.
